import type { Metadata } from "next";
import { Tomorrow } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";


const tomorrow = Tomorrow({ 
  subsets: ["latin"], 
  weight: ["400"] 
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={`${tomorrow.className} antialiased flex justify-center`}
      >
        <main className="container flex flex-col justify-between">
          <Header/>
          {children}
          <Footer/>
        </main>
      </body>
    </html>
  );
}
